version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    assignees:
      - "NelsonBN"
    reviewers:
      - "NelsonBN"
    commit-message:
      prefix: "GitHubActions"
      include: "scope"
    target-branch: "develop"

  # Nuget packages
  - package-ecosystem: "nuget"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    assignees:
      - "NelsonBN"
    reviewers:
      - "NelsonBN"
    commit-message:
      prefix: "NuGet"
      include: "scope"
    target-branch: "develop"
