using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.AspNetCore.Mvc;
using PowerUtils.AspNetCore.ErrorHandler.Serializers;

namespace PowerUtils.AspNetCore.ErrorHandler
{
    [JsonConverter(typeof(ErrorProblemDetailsJsonConverter))]
    [Obsolete("This package has been discontinued because it never evolved, and the code present in this package does not justify its continuation. It is preferable to implement this code directly in the project if necessary.")]
    public class ErrorProblemDetails : ProblemDetails
    {
        /// <summary>
        /// ID generated by the problem to track logs
        /// </summary>
        [JsonPropertyName("traceId")]
        [Obsolete("This package has been discontinued because it never evolved, and the code present in this package does not justify its continuation. It is preferable to implement this code directly in the project if necessary.")]
        public string TraceId { get; set; }

        /// <summary>
        /// List of errors
        /// </summary>
        /// <example>
        /// { "source": { "code: "", "description": "" } }
        /// </example>
        [Obsolete("This package has been discontinued because it never evolved, and the code present in this package does not justify its continuation. It is preferable to implement this code directly in the project if necessary.")]
        public IDictionary<string, ErrorDetails> Errors { get; set; } = new Dictionary<string, ErrorDetails>(StringComparer.InvariantCultureIgnoreCase);

        /// <summary>
        /// Initializes a new instance of <see cref="ErrorProblemDetails"/>.
        /// </summary>
        [Obsolete("This package has been discontinued because it never evolved, and the code present in this package does not justify its continuation. It is preferable to implement this code directly in the project if necessary.")]
        public ErrorProblemDetails() { }

        /// <summary>
        /// Serialize problem details to JSON
        /// </summary>
        [Obsolete("This package has been discontinued because it never evolved, and the code present in this package does not justify its continuation. It is preferable to implement this code directly in the project if necessary.")]
        public override string ToString()
            => JsonSerializer.Serialize(this);

        [Obsolete("This package has been discontinued because it never evolved, and the code present in this package does not justify its continuation. It is preferable to implement this code directly in the project if necessary.")]
        public static implicit operator string(ErrorProblemDetails problemDetailsResponse)
            => problemDetailsResponse.ToString();
    }


    [Obsolete("This package has been discontinued because it never evolved, and the code present in this package does not justify its continuation. It is preferable to implement this code directly in the project if necessary.")]
    public class ErrorDetails
    {
        /// <summary>
        /// Error code
        /// </summary>
        [JsonPropertyName("code")]
        [Obsolete("This package has been discontinued because it never evolved, and the code present in this package does not justify its continuation. It is preferable to implement this code directly in the project if necessary.")]
        public string Code { get; set; }


        /// <summary>
        /// A human-readable explanation specific to this occurrence of the error.
        /// </summary>
        [JsonPropertyName("description")]
        [Obsolete("This package has been discontinued because it never evolved, and the code present in this package does not justify its continuation. It is preferable to implement this code directly in the project if necessary.")]
        public string Description { get; set; }

        [Obsolete("This package has been discontinued because it never evolved, and the code present in this package does not justify its continuation. It is preferable to implement this code directly in the project if necessary.")]
        public ErrorDetails() { }
        [Obsolete("This package has been discontinued because it never evolved, and the code present in this package does not justify its continuation. It is preferable to implement this code directly in the project if necessary.")]
        public ErrorDetails(
            string code,
            string description)
        {
            Code = code;
            Description = description;
        }

        [Obsolete("This package has been discontinued because it never evolved, and the code present in this package does not justify its continuation. It is preferable to implement this code directly in the project if necessary.")]
        public override string ToString()
            => JsonSerializer.Serialize(this);

        [Obsolete("This package has been discontinued because it never evolved, and the code present in this package does not justify its continuation. It is preferable to implement this code directly in the project if necessary.")]
        public static implicit operator string(ErrorDetails errorDetails)
            => errorDetails.ToString();
    }
}
