using System.Collections.Generic;
using System.Text.Json;

namespace PowerUtils.AspNetCore.ErrorHandler
{
    public class ProblemDetailsResponse
    {
        #region PROPERTIES
        /// <summary>
        /// The HTTP status code([RFC7231], Section 6) generated
        /// </summary>
        public int Status { get; set; }

        /// <summary>
        /// A URI reference [RFC3986] that identifies the problem type
        /// </summary>
        public string Type { get; set; }

        /// <summary>
        /// A short, human-readable summary of the problem type. see[RFC7231], Section 3.4
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// A URI reference that identifies the specific occurrence of the problem
        /// </summary>
        public string Instance { get; set; }

        /// <summary>
        /// ID generated by the problem to track logs
        /// </summary>
        public string TraceID { get; set; }

        /// <summary>
        /// Error property list
        /// </summary>
        /// <example>
        /// { "Property": "Error" }
        /// </example>
        public IDictionary<string, string> Errors { get; set; }
        #endregion

        /// <summary>
        /// Serialize problem details to JSON
        /// </summary>
        /// <returns></returns>
        public override string ToString()
            => JsonSerializer.Serialize(this);

        public static implicit operator string(ProblemDetailsResponse problemDetailsResponse)
            => problemDetailsResponse.ToString();
    }
}
