name: 'Publish nuget'



on:
  push:
    branches:
      - deploy-nuget



env:
  SDK_VERSION: '6.0.300'
  PACKAGE_PATH: ./src/**/*.nupkg
  NUGET_SERVER: https://api.nuget.org/v3/index.json



jobs:

  deploy-nuget:
    name: "Deploy nuget"
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v3

    - name: "Setup .NET"
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.SDK_VERSION }}

    - name: "Restore dependencies"
      run: dotnet restore

    - name: "Build"
      run: dotnet build --configuration Release --no-restore

    - name: "Test"
      run: dotnet test --configuration Release --no-build

    - name: "Pack"
      run: dotnet pack --configuration Release --no-build

    - name: "Publish nuget"
      run: dotnet nuget push ${{ env.PACKAGE_PATH }} --api-key ${{ secrets.NUGET_TOKEN }} --source ${{ env.NUGET_SERVER }} --skip-duplicate
