name: 'Tests'

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main


jobs:

  test-project:
    name: "Testing project"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.201'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build
